---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logstash-deployment
  namespace: logstash
  labels:
    app: logstash-es
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash-es
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:6.8.4
        ports:
        - containerPort: 5044
          name: beats
          protocol: TCP
        env:
        - name: ES_VERSION
          value: 6.3.0
        - name: ES_DOMAIN
          value: ""
        - name: LS_JAVA_OPTS
          value: -Xmx2g -Xms2g
        volumeMounts:
          - name: config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-volume
            mountPath: /usr/share/logstash/pipeline
        resources:
          limits:
            cpu:    1
            memory: 2Gi
          requests:
            cpu:    0.5
            memory: 2Gi
      volumes:
      - name: config-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.yml
              path: logstash.yml
            - key: jvm.options
              path: jvm.options
            - key: metricbeat-template.json
              path: metricbeat-template.json
      - name: logstash-pipeline-volume
        configMap:
          name: logging-configmap
          items:
            - key: logstash.conf
              path: logstash.conf
