apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: gcr.io/google_samples/gb-redisslave:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # Using `GET_HOSTS_FROM=dns` requires your cluster to
          # provide a dns service. As of Kubernetes 1.3, DNS is a built-in
          # service launched automatically. However, if the cluster you are using
          # does not have a built-in DNS service, you can instead
          # access an environment variable to find the master
          # service's host. To do so, comment out the 'value: dns' line above, and
          # uncomment the line below:
          # value: env
        ports:
        - containerPort: 6379
      - name: redis-statistic
        image: fluent/fluent-bit:0.14.6
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        command: ["/bin/bash", "-c"]
        args:
        - |
          bash /bin/fluentbit_entrypoint.sh
        volumeMounts:
          - name: fluentd-config
            mountPath: /bin/redis_stats.py
            subPath: redis_stats
          - name: fluentd-config
            mountPath: /bin/fluentbit_entrypoint.sh
            subPath: fluentbit_entrypoint
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config